<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>TheLibrary</AssemblyName>
    <RootNamespace>TheLibrary</RootNamespace>
    <Version>1.0.0</Version>
    <Product>The Library</Product>
    <Company>ByteBrew</Company>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <InvariantGlobalization>false</InvariantGlobalization>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <Resource Include="logo.png" />
  </ItemGroup>

</Project>
